image: golang:1.23-bullseye

stages:
  - test
  - build
  - upload

variables:
  CI_PACKAGE_URL: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/create-array/${CI_JOB_TOKEN}'

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p bin
    - make all
  artifacts:
    paths:
      - bin
  rules:
    - if: $CI_COMMIT_TAG

package:
  stage: upload
  script:
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/create-array-linux $CI_PACKAGE_URL/create-array-linux'
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/create-array-windows $CI_PACKAGE_URL/create-array-windows'
    - 'curl --fail-with-body --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/create-array-darwin $CI_PACKAGE_URL/create-array-darwin'
  rules:
    - if: $CI_COMMIT_TAG
